class Stack:
    def __init__(self):
        self.a=[3,2,1]
        self.b=[]
        self.c=[]

    def push(self,ele,lis):
        lis.append(ele)

    def pop(self,lis):
        self.val=lis.pop()

print("Given that INPUT \t A=[3,2,1]\tB=[]\tC=[]")
print("Expected OUTPUT \t A=[]\t\tB=[]\tC=[3,2,1]")
obj=Stack()
print("---------------------------------------------")
print("A=",obj.a,"\tB=",obj.b,"\t\tC=",obj.c)
print("")
print("Pass One Completed!!")
obj.pop(obj.a)
obj.push(obj.val,obj.c)
print("---------------------------------------------")
print("A=",obj.a,"\tB=",obj.b,"\t\tC=",obj.c)
print("")
print("Pass Two Completed!!")
obj.pop(obj.a)
obj.push(obj.val,obj.b)
print("---------------------------------------------")
print("A=",obj.a,"\t\tB=",obj.b,"\t\tC=",obj.c)
print("")
print("Pass Three Completed!!")
obj.pop(obj.c)
obj.push(obj.val,obj.b)
print("---------------------------------------------")
print("A=",obj.a,"\t\tB=",obj.b,"\tC=",obj.c)
print("")
print("Pass Four Completed!!")
obj.pop(obj.a)
obj.push(obj.val,obj.c)
print("---------------------------------------------")
print("A=",obj.a,"\t\tB=",obj.b,"\tC=",obj.c)
print("")
print("Pass Five Completed!!")
obj.pop(obj.b)
obj.push(obj.val,obj.a)
print("---------------------------------------------")
print("A=",obj.a,"\t\tB=",obj.b,"\t\tC=",obj.c)
print("")
print("Pass Six Completed!!")
obj.pop(obj.b)
obj.push(obj.val,obj.c)
print("---------------------------------------------")
print("A=",obj.a,"\t\tB=",obj.b,"\t\tC=",obj.c)
print("")
print("Pass Seven Completed!!")
obj.pop(obj.a)
obj.push(obj.val,obj.c)
print("---------------------------------------------")
print("A=",obj.a,"\t\tB=",obj.b,"\t\tC=",obj.c)
print("")
print("Pass Eight Completed!!")